baseURL = "https://www.felker.org/"
languageCode = "de-de"
defaultContentLanguage = "de"
title = "Rolf Felker – CV"
theme = "almeida-cv"
disableHugoGeneratorInject = true
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#444"
colorPageBackground = "#ddd"
colorPrimary = "#c0392b"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#c0392b"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#555"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#c0392b"
pages = 2
swapColumns = false
footerNote = "Rolf Felker · felker.org"
